### ISSUE TITLE
Add mission details in Terminal

### ISSUE THREAD

**Issue by ambid17** [CaosCreations/SpaceTruckin#39]
After accepting a mission in the notice board, there's no way to look at the mission's details.

The details should be added to the missions panel in the office terminal

**Comment by maxwellpark** [comment]
Update: Stef said the details should be in line with the mission they relate to, and positioned on the opposite side of the screen (right hand side). See mockup below:
![mockup](https://user-images.githubusercontent.com/61809127/103108283-661c9d00-463e-11eb-9128-5bf4cc495ce2.png)
